#   Postgres:
#     User:          postgres
#     Password:      secret
version: '3.1'
services:
  database:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_PASSWORD: secret      
      # POSTGRES_DB: directus
    ports:
      - 5432:5432
    volumes:
      - ./dummy_dump.sql:/docker-entrypoint-initdb.d/dummy_dump.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    env_file: ./dbms/.env
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    volumes:
      - ./dbms/extensions/:/directus/extensions/
      - ./dbms/uploads:/directus/uploads