#   Postgres:
#     User:          postgres
#     Password:      secret
version: '3.1'
services:
  postgres:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: directus
    ports:
      - 5432:5432
